# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3fac67fa28bf469eaea39d74c498a8ad"
name = "static-product-tables"
handle = "static-product-tables"
application_url = "https://fast-desert-c-translations.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "rackyard.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://fast-desert-c-translations.trycloudflare.com/auth/callback",
  "https://fast-desert-c-translations.trycloudflare.com/auth/shopify/callback",
  "https://fast-desert-c-translations.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
